[package]
name = "pallium"
version = "0.1.0"
authors = [
    "Anton Zhuravlev <froggrog@hotmail.com>"
    ]

[workspace]
members = [
    "abci-rs"
]

[[bin]]
name = "pallium"
path = "src/main.rs"

[dependencies]
abci-rs = { git = "https://github.com/neocortexlab/abci-rs" }
clap = "^2.31.2"
